// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaKJnbrXyg61O4D9FYygES21Wv6cxwIk',
    appId: '1:768457556313:web:eb2c5d58a35b4bc885cc48',
    messagingSenderId: '768457556313',
    projectId: 'weight-mate-project',
    authDomain: 'weight-mate-project.firebaseapp.com',
    storageBucket: 'weight-mate-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOt99A6Q4Gw1RVgSLWfatRB-k_f2HdKo',
    appId: '1:768457556313:android:e5c0bcd11e7b049485cc48',
    messagingSenderId: '768457556313',
    projectId: 'weight-mate-project',
    storageBucket: 'weight-mate-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgAYbM9ubQOCV-9xJe2T0CUNrSDIniAg',
    appId: '1:768457556313:ios:55097bf7ada231d885cc48',
    messagingSenderId: '768457556313',
    projectId: 'weight-mate-project',
    storageBucket: 'weight-mate-project.appspot.com',
    iosBundleId: 'com.kthdd.weightMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOgAYbM9ubQOCV-9xJe2T0CUNrSDIniAg',
    appId: '1:768457556313:ios:5b6ce273aeabafff85cc48',
    messagingSenderId: '768457556313',
    projectId: 'weight-mate-project',
    storageBucket: 'weight-mate-project.appspot.com',
    iosBundleId: 'com.example.flutterAppWeightManagement',
  );
}
